import mongoose from "mongoose";

const messageSchema = new mongoose.Schema(
  {
    senderId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    receiverId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    text: {
      type: String,
    },
    image: {
      type: String,
    },

    // ── Moderation fields (added for toxicity detection) ──────────────

    toxicityScore: {
      type: Number,
      default: 0,
      min: 0,
      max: 1,
    },

    isToxic: {
      type: Boolean,
      default: false,
    },

    moderationCategories: {
      type: Map,
      of: Boolean,
      default: {},
    },

    flaggedAt: {
      type: Date,
      default: null,
    },

    // ── AI Chatbot fields ─────────────────────────────────────────────

    // True if this message was generated by the AI bot
    isAI: {
      type: Boolean,
      default: false,
    },

    // Stores the original @AI question this reply is responding to
    // Useful for context display in the UI
    aiPrompt: {
      type: String,
      default: null,
    },
  },
  { timestamps: true }
);

// Index for fast admin queries like: Message.find({ isToxic: true })
messageSchema.index({ isToxic: 1, flaggedAt: -1 });

const Message = mongoose.model("Message", messageSchema);

export default Message;